ALTER TABLE `claw_skills`
ADD `skill_uid` varchar(64),
ADD `program_id` varchar(128) DEFAULT 'CLAW_SKILL_PROGRAM_V1',
ADD `registry_account` varchar(128),
ADD `skill_account` varchar(128),
ADD `current_version_account` varchar(128),
ADD `current_version` varchar(32) DEFAULT '1.0.0',
ADD `author_wallet` varchar(128),
ADD `tags` text,
ADD `status` enum('draft','published','active','paused','deprecated','archived') NOT NULL DEFAULT 'draft',
ADD `usage_count` int NOT NULL DEFAULT 0,
ADD `success_count` int NOT NULL DEFAULT 0,
ADD `failure_count` int NOT NULL DEFAULT 0,
ADD `reputation_score` int NOT NULL DEFAULT 0,
ADD `content_hash` varchar(128),
ADD `latest_version_hash` varchar(128),
ADD `previous_version_account` varchar(128),
ADD `previous_version_hash` varchar(128),
ADD `canonical_uri` text,
ADD `metadata_uri` text,
ADD `storage_ref` text,
ADD `proof_ref` text,
ADD `notes` text,
ADD `flags` text,
ADD `chain_id` int NOT NULL DEFAULT 101,
ADD `explorer_tx_hash` varchar(128),
ADD `explorer_url` text,
ADD `published_at` timestamp,
ADD `last_used_at` timestamp,
ADD `last_resolved_at` timestamp,
ADD `last_verified_at` timestamp,
ADD `sync_state` enum('ok','degraded','offline') NOT NULL DEFAULT 'ok';
--> statement-breakpoint
CREATE TABLE `claw_skill_versions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`skill_uid` varchar(64) NOT NULL,
	`version` varchar(32) NOT NULL,
	`version_account` varchar(128) NOT NULL,
	`previous_version_account` varchar(128),
	`content_hash` varchar(128) NOT NULL,
	`author_wallet` varchar(128) NOT NULL,
	`status` enum('draft','published','active','paused','deprecated','archived') NOT NULL DEFAULT 'published',
	`description` text,
	`tags` text,
	`changelog` text,
	`payload` text,
	`canonical_uri` text,
	`metadata_uri` text,
	`tx_hash` varchar(128),
	`explorer_url` text,
	`published_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `claw_skill_versions_id` PRIMARY KEY(`id`)
);
