import type { ErrorCode, ErrorScope, ErrorSeverity } from "./errorTypes";

export interface ErrorCatalogEntry {
  scope: ErrorScope;
  severity: ErrorSeverity;
  title: string;
  message: string;
  recoveryAction?: string;
  retryLabel?: string;
  supportHint?: string;
}

export const ERROR_CATALOG: Record<ErrorCode, ErrorCatalogEntry> = {
  WALLET_NOT_CONNECTED: {
    scope: "wallet",
    severity: "warning",
    title: "Wallet not connected",
    message: "Connect a Solana wallet to bind identity and anchor receipts.",
    recoveryAction: "Open the wallet panel and approve a connection.",
    retryLabel: "Connect wallet",
  },
  WALLET_CONNECTION_REJECTED: {
    scope: "wallet",
    severity: "warning",
    title: "Wallet connection rejected",
    message: "The wallet declined the connection request.",
    recoveryAction: "Try again or choose a different wallet.",
    retryLabel: "Retry connection",
  },
  WALLET_SESSION_SIGN_FAILED: {
    scope: "session",
    severity: "warning",
    title: "Session signature failed",
    message: "The wallet did not sign the session challenge.",
    recoveryAction: "Approve the signature request or refresh the session.",
    retryLabel: "Sign again",
  },
  WALLET_SESSION_EXPIRED: {
    scope: "session",
    severity: "warning",
    title: "Session expired",
    message: "Reconnect your Solana wallet to continue with a fresh session.",
    recoveryAction: "Disconnect and connect again, then complete verification.",
    retryLabel: "Refresh session",
  },
  WALLET_WRONG_CLUSTER: {
    scope: "wallet",
    severity: "warning",
    title: "Wrong Solana cluster",
    message: "Switch to the cluster this command center expects (e.g. devnet for this demo).",
    recoveryAction: "Change network in your wallet to match the app cluster.",
    retryLabel: "After switching network",
  },
  WALLET_UNSUPPORTED: {
    scope: "wallet",
    severity: "error",
    title: "Wallet not supported",
    message: "This wallet adapter is not supported for this flow.",
    recoveryAction: "Use a compatible Solana wallet (e.g. Phantom, Backpack).",
  },
  SESSION_VERIFICATION_FAILED: {
    scope: "session",
    severity: "error",
    title: "Session verification failed",
    message: "The server could not verify your wallet session.",
    recoveryAction: "Complete the session signature flow again.",
    retryLabel: "Verify session",
  },
  SESSION_TOKEN_EXPIRED: {
    scope: "session",
    severity: "warning",
    title: "Session token expired",
    message: "Your session token is no longer valid.",
    recoveryAction: "Sign in or refresh the wallet session.",
    retryLabel: "Refresh session",
  },
  SESSION_REQUIRED: {
    scope: "session",
    severity: "warning",
    title: "Verified session required",
    message: "An active, verified wallet session is required for this step.",
    recoveryAction: "Connect and complete session verification before anchoring.",
    retryLabel: "Verify session",
  },
  RPC_UNAVAILABLE: {
    scope: "rpc",
    severity: "critical",
    title: "Solana RPC unavailable",
    message: "The cluster RPC endpoint is not reachable.",
    recoveryAction: "Wait and retry, or check RPC configuration.",
    retryLabel: "Retry",
    supportHint: "If this persists, the network or your RPC provider may be down.",
  },
  RPC_TIMEOUT: {
    scope: "rpc",
    severity: "error",
    title: "RPC timeout",
    message: "The Solana RPC did not respond in time.",
    recoveryAction: "Retry the operation; congestion often clears quickly.",
    retryLabel: "Retry",
  },
  RPC_RATE_LIMITED: {
    scope: "rpc",
    severity: "warning",
    title: "RPC rate limited",
    message: "Too many requests were sent to the RPC endpoint.",
    recoveryAction: "Wait briefly and retry, or use a dedicated RPC URL.",
    retryLabel: "Retry after wait",
  },
  TX_BUILD_FAILED: {
    scope: "transaction",
    severity: "error",
    title: "Transaction build failed",
    message: "The transaction could not be constructed.",
    recoveryAction: "Check accounts and program ID, then retry.",
    retryLabel: "Retry",
  },
  TX_SIMULATION_FAILED: {
    scope: "transaction",
    severity: "error",
    title: "Simulation failed",
    message: "The transaction simulation reported a failure before send.",
    recoveryAction: "Review logs for program errors or insufficient funds.",
    retryLabel: "Retry after fix",
  },
  TX_SEND_FAILED: {
    scope: "transaction",
    severity: "error",
    title: "Transaction failed to send",
    message: "The signed transaction could not be submitted to the cluster.",
    recoveryAction: "Retry send; if it persists, check RPC and wallet.",
    retryLabel: "Retry send",
  },
  TX_CONFIRMATION_FAILED: {
    scope: "transaction",
    severity: "error",
    title: "Confirmation failed",
    message: "The transaction was sent but confirmation did not complete.",
    recoveryAction: "Check the signature on the explorer or retry confirmation.",
    retryLabel: "Recheck explorer",
  },
  TX_EXPIRED: {
    scope: "transaction",
    severity: "warning",
    title: "Transaction expired",
    message: "The blockhash expired before the transaction landed.",
    recoveryAction: "Rebuild and sign a fresh transaction.",
    retryLabel: "Retry",
  },
  ACCOUNT_NOT_FOUND: {
    scope: "account",
    severity: "error",
    title: "Account not found",
    message: "The requested on-chain account does not exist.",
    recoveryAction: "Initialize the account or switch cluster.",
  },
  ACCOUNT_DECODE_FAILED: {
    scope: "account",
    severity: "error",
    title: "Account decode failed",
    message: "Account data could not be decoded with the expected layout.",
    recoveryAction: "Check program deployment and IDL version.",
  },
  PDA_DERIVATION_FAILED: {
    scope: "account",
    severity: "error",
    title: "PDA derivation failed",
    message: "A program-derived address could not be derived for this path.",
    recoveryAction: "Verify seeds and program id.",
  },
  PROGRAM_ERROR: {
    scope: "anchor",
    severity: "error",
    title: "Program error",
    message: "The on-chain program returned an error.",
    recoveryAction: "Inspect simulation logs and program error code.",
  },
  ANCHOR_IDL_MISMATCH: {
    scope: "anchor",
    severity: "critical",
    title: "IDL mismatch",
    message: "The IDL does not match the deployed program.",
    recoveryAction: "Redeploy or refresh the IDL used by the client and server.",
  },
  INSUFFICIENT_SOL: {
    scope: "solana",
    severity: "warning",
    title: "Insufficient SOL",
    message: "The wallet does not have enough SOL for fees and rent.",
    recoveryAction: "Fund the wallet on this cluster.",
  },
  INSUFFICIENT_PERMISSIONS: {
    scope: "backend",
    severity: "error",
    title: "Insufficient permissions",
    message: "This wallet or session cannot perform the requested action.",
    recoveryAction: "Use an authorized wallet or complete verification.",
  },
  RECEIPT_ANCHOR_FAILED: {
    scope: "receipt",
    severity: "error",
    title: "Receipt anchor failed",
    message: "The receipt could not be anchored on Solana.",
    recoveryAction: "Your draft is preserved; retry anchor after fixing the session or RPC.",
    retryLabel: "Retry anchor",
  },
  PROOF_VERIFICATION_FAILED: {
    scope: "proof",
    severity: "warning",
    title: "Proof pending verification",
    message: "A signature exists but explorer verification did not succeed yet.",
    recoveryAction: "Recheck proof status; data may still be valid.",
    retryLabel: "Verify again",
  },
  MEMORY_WRITE_FAILED: {
    scope: "memory",
    severity: "error",
    title: "Memory write failed",
    message: "Reflection or memory could not be written.",
    recoveryAction: "Retry after checking backend and storage.",
    retryLabel: "Retry write",
  },
  MEMORY_RETRIEVE_FAILED: {
    scope: "memory",
    severity: "error",
    title: "Memory retrieve failed",
    message: "Stored memory could not be loaded.",
    recoveryAction: "Retry; cached data may still display.",
    retryLabel: "Retry load",
  },
  REFLECTION_WRITE_FAILED: {
    scope: "reflection",
    severity: "error",
    title: "Reflection write failed",
    message: "The reflection step did not complete.",
    recoveryAction: "Execution may still exist; retry reflection or anchor.",
    retryLabel: "Retry reflection",
  },
  SKILL_PUBLISH_FAILED: {
    scope: "skill",
    severity: "error",
    title: "Skill publish failed",
    message: "The skill could not be published.",
    recoveryAction: "Fix validation errors and retry publish.",
    retryLabel: "Retry publish",
  },
  SKILL_UPDATE_FAILED: {
    scope: "skill",
    severity: "error",
    title: "Skill update failed",
    message: "The skill version could not be updated.",
    recoveryAction: "Retry after resolving on-chain or registry errors.",
    retryLabel: "Retry update",
  },
  PLAN_BUILD_FAILED: {
    scope: "plan",
    severity: "error",
    title: "Plan build failed",
    message: "The execution plan could not be built or anchored.",
    recoveryAction: "Preserved goal and skill selection can be retried.",
    retryLabel: "Retry plan",
  },
  EXECUTION_FAILED: {
    scope: "execution",
    severity: "error",
    title: "Execution failed",
    message: "The autonomous execution path did not complete successfully.",
    recoveryAction: "Review errors below; partial receipts may still be available.",
    retryLabel: "Retry execution",
  },
  OPENCLAW_IMPORT_FAILED: {
    scope: "openclaw",
    severity: "error",
    title: "OpenClaw import failed",
    message: "Manifest or tool import through OpenClaw failed.",
    recoveryAction: "Check bridge health and payload format.",
    retryLabel: "Retry import",
  },
  OPENCLAW_EXPORT_FAILED: {
    scope: "openclaw",
    severity: "error",
    title: "OpenClaw export failed",
    message: "Export to OpenClaw-compatible format failed.",
    recoveryAction: "Retry after bridge recovery.",
    retryLabel: "Retry export",
  },
  ZERO_G_STORAGE_FAILED: {
    scope: "zerog",
    severity: "error",
    title: "Storage upload failed",
    message: "0G storage upload did not complete.",
    recoveryAction: "Receipt may be degraded; retry upload when storage is healthy.",
    retryLabel: "Retry upload",
  },
  ZERO_G_DA_FAILED: {
    scope: "zerog",
    severity: "error",
    title: "DA batch failed",
    message: "0G data availability batching did not complete.",
    recoveryAction: "Mark partial commitment; retry DA when available.",
    retryLabel: "Retry DA",
  },
  ZERO_G_VERIFY_FAILED: {
    scope: "zerog",
    severity: "warning",
    title: "0G verify failed",
    message: "Blob or batch verification against 0G did not succeed.",
    recoveryAction: "Retry verification or use an alternate proof path.",
    retryLabel: "Retry verify",
  },
  DB_WRITE_FAILED: {
    scope: "database",
    severity: "critical",
    title: "Database write failed",
    message: "A persistent write to the database failed.",
    recoveryAction: "Retry; if critical, check DB connectivity.",
    retryLabel: "Retry",
  },
  DB_READ_FAILED: {
    scope: "database",
    severity: "error",
    title: "Database read failed",
    message: "Data could not be read from the database.",
    recoveryAction: "Retry; last cached snapshot may still show.",
    retryLabel: "Retry",
  },
  INDEXER_SYNC_FAILED: {
    scope: "indexer",
    severity: "warning",
    title: "Indexer sync failed",
    message: "The indexer could not sync chain or receipt state.",
    recoveryAction: "Proof may show as pending until sync recovers.",
    retryLabel: "Retry sync",
  },
  UNEXPECTED_ROUTE_ERROR: {
    scope: "backend",
    severity: "critical",
    title: "Request failed",
    message: "The server hit an unexpected error handling this request.",
    recoveryAction: "Retry; if it repeats, capture request id from diagnostics.",
    retryLabel: "Retry",
  },
  VALIDATION_FAILED: {
    scope: "backend",
    severity: "warning",
    title: "Validation failed",
    message: "The request payload did not pass validation.",
    recoveryAction: "Fix the highlighted fields and submit again.",
  },
  DEMO_MODE_MISMATCH: {
    scope: "demo",
    severity: "info",
    title: "Demo mode only",
    message: "This path is simulated or fixture-backed — not asserted as live verification.",
    recoveryAction: "Switch to live mode for real chain proofs when configured.",
  },
  DEGRADED_MODE: {
    scope: "backend",
    severity: "warning",
    title: "Degraded mode",
    message: "Some integrations are unhealthy; the app continues with reduced guarantees.",
    recoveryAction: "Retry failed steps when services recover.",
    retryLabel: "Retry",
  },
  UNKNOWN: {
    scope: "unknown",
    severity: "error",
    title: "Request error",
    message: "An error occurred that could not be classified.",
    recoveryAction: "Retry or open diagnostics for technical detail.",
    retryLabel: "Retry",
  },
};

export function catalogEntry(code: ErrorCode): ErrorCatalogEntry {
  return ERROR_CATALOG[code] ?? ERROR_CATALOG.UNKNOWN;
}
